import { Doctor } from "./doctor";

// this is a custom search Result on Dahboard UI for Doctor
export interface CustomRevenue {
    doctor: Doctor;

    fromDate: string;
    tillDate: string;

    // Earning appointment fees
    earningByAppointmentFee: string;

    // Earning by selling Medicine & Equipment from thier own Chemist ( if any )
    earningByChemist: string;

    // Number of prescriptions not Buyed by our Chemist
    nonDeliveredPrescriptionsCount: number;

    // Total Revenue generated by Chemist by selling Medicine and MedicalEquipment
    totalCostRevenueByChemist: string;

    // Doctor has to calculate himself if Patient got it tested from the referred center
    medicalTestsReferred: number;

}